### ISSUE TITLE
[Feature request] Review approval when no warnings

### ISSUE THREAD

**Issue by yassinecc** [grodowski/pronto-undercover#10]
Hi there, we are seeing that pronto-undercover does not update its review after coverage changes. Typically:
- First commit is pushed, Pronto adds a review comment with uncovered lines
- Author takes heed and pushes a second commit which addresses missing coverage
- Pronto does not amend its review or add another one

We have included a `PRONTO_PULL_REQUEST_ID="$TRAVIS_PULL_REQUEST" unbuffer bundle exec pronto run -f github_pr -c origin/master;` step in our Travis script, wondering if there was an issue with our config?

Or it could be a new feature to have the bot approve PRs if undercover exits with 0?

**Comment by grodowski** [comment]
Hi @yassinecc! Thanks for submitting this issue. Yeah, it's a bit annoying that pronto comments don't disappear on new changes. I've experienced this with other pronto runners too, but IMO this issue might be more related to pronto itself than this undercover runner. Have you tried using the `github_pr_review` formatter ([documented here](https://github.com/prontolabs/pronto#github-integration)) instead of `github_pr`?
